// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYZVV750LdK8732pdQWzMMkRXupreuaZ8',
    appId: '1:741272595583:web:65f6981b6777867b20e34a',
    messagingSenderId: '741272595583',
    projectId: 'chatapptute-68be0',
    authDomain: 'chatapptute-68be0.firebaseapp.com',
    storageBucket: 'chatapptute-68be0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxmKQ7acDUP7pY4XcrrjLdGL8jrxF_pWI',
    appId: '1:741272595583:android:0acdc70c73ad23ab20e34a',
    messagingSenderId: '741272595583',
    projectId: 'chatapptute-68be0',
    storageBucket: 'chatapptute-68be0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn3hM1rtERyrwbvROpOk7UPChA7lcI6rc',
    appId: '1:741272595583:ios:a4f2657d0934fe9920e34a',
    messagingSenderId: '741272595583',
    projectId: 'chatapptute-68be0',
    storageBucket: 'chatapptute-68be0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn3hM1rtERyrwbvROpOk7UPChA7lcI6rc',
    appId: '1:741272595583:ios:a4f2657d0934fe9920e34a',
    messagingSenderId: '741272595583',
    projectId: 'chatapptute-68be0',
    storageBucket: 'chatapptute-68be0.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYZVV750LdK8732pdQWzMMkRXupreuaZ8',
    appId: '1:741272595583:web:a2dbdcd5311901f620e34a',
    messagingSenderId: '741272595583',
    projectId: 'chatapptute-68be0',
    authDomain: 'chatapptute-68be0.firebaseapp.com',
    storageBucket: 'chatapptute-68be0.appspot.com',
  );
}
